name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/docs-of-easinteraction
            Trigger: `${{ github.ref_name }}` `${{ github.event.commits[0].id }}`

  build:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      # used by dependencies cache
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm docs:build
      # used by official deploy action
      - uses: actions/upload-pages-artifact
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Send end message to telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions End
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/docs-of-easinteraction
            Trigger: `${{ github.ref_name }}` `${{ github.event.commits[0].id }}`
